image: node:lts

pages:
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install
    - npm run build
  script:
    - echo "ğŸµ DagKlassical - Build completado"
    - ls -la public/  # â† Ver quÃ© archivos hay
    - echo "ğŸµ Build completado"
  artifacts:
    paths:
      - public/  # â† VOLVEMOS A public
  only:
    - main
 